### ISSUE TITLE
ember app code challenge

### ISSUE THREAD

**Issue by nelsonomuto** [nelsonomuto/power-auctions-ember-app#2]
# power-auctions-ember-app
ember app code challenge

Ember tutorial app: https://guides.emberjs.com/release/tutorial/part-1/ 

## TODOs
- [x] open PRs with descriptions and self merge
- [x] add ember-cli-typescript and convert at least one component class to it (https://docs.ember-cli-typescript.com/)
- [x] write at least one unit test, component test, and application test
- [x] add 1 feature that you come up with yourself
